// Generated by CoffeeScript 1.7.1
(function() {
  var Q, baseUrl, cx, https, imgType, key, num, safe, searchType;

  https = require("https");

  Q = require("q");

  cx = '017716653312651474242%3Af1wy4gpl-78';

  key = 'AIzaSyAwNFSNnkwld4r-GF3yYcaH0DBkpbck6sw';

  num = 1;

  safe = 'high';

  searchType = 'image';

  imgType = '';

  baseUrl = 'https://www.googleapis.com/customsearch/v1?';

  exports.findImage = function(keyword) {
    var deferred, url;
    deferred = Q.defer();
    keyword = keyword.replace('%', '');
    console.log("In here yo!");
    url = "" + baseUrl + "q=" + keyword + "&cx=" + cx + "&key=" + key + "&num=" + num + "&safe=" + safe + "&searchType=" + searchType + "&rights=cc_publicdomain+cc_noncommercial";
    https.get(url, function(stream) {
      var buffer;
      console.log(url);
      buffer = "";
      stream.on('data', function(packet) {
        return buffer += packet;
      });
      return stream.on('end', function() {
        var data, imageLink;
        console.log("Buffer is: ");
        console.log(buffer);
        data = JSON.parse(buffer);
        console.log(buffer);
        if ((data != null) && (data.items != null) && data.items.length > 0) {
          console.log("GOOD");
          imageLink = data.items[0].link;
          return deferred.resolve(imageLink);
        } else {
          console.log("BAD");
          return deferred.reject();
        }
      });
    });
    return deferred.promise;
  };

}).call(this);
